name: Android iOs Release Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Android Release Build

    env:
      my_repo: "algoramming/bangla_handwritten_math_solver_flutter_app"
      my_secret: "${{secrets.CAPSTONE_PROJECT}}"
      my_tag: "v1.0.${{github.run_number}}"

    # This job will run on macos virtual machine
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - run: |
          echo "Your Repo is $my_repo"
          echo "Your secrect token is $my_secret"
          echo "Your tag is $my_tag"

      # Setup Java environment.
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18.x"

      # Setup the flutter environment.
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter config --enable-android
      - run: flutter config --enable-ios
      - run: flutter clean
      - run: flutter pub get

      # Flutter android apk build command.
      - run: flutter build apk
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      # Flutter ios ipa build command.
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # Upload assets to release
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*,build/ios/iphoneos/app.ipa,build/app/outputs/bundle/release/app-release.aab"
          tag: ${{env.my_tag}}
          token: ${{env.my_secret}}
